#!/bin/bash

# What modules, in what order
MODULES="backlight volume cputemp nvidia_gpu_temp wifi cpuload ram disksize battery time"

# Modules that require an active internet connection
ONLINE_MODULES="weather internet"

# Delay between showing the status bar
DELAY="0.05"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beginning of the status bar
RIGHT_PADDING=" "
LEFT_PADDING=" "
