#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr

# Autostart Applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore & 
dunst &
polybar &

