#!/usr/bin/env bash
dir="$HOME/.config/rofi/launchers/type-1"
theme='style-11'

choice=$(fd -e pdf -e djvu --base-directory ~ | rofi -dmenu -theme ${dir}/${theme}.rasi -i -matching fuzzy)

[[ -z "$choice" ]] || brave ~/"$choice"
